### ISSUE TITLE
On pressing the Action Floating button , it gives a blue color, although button is black

### ISSUE THREAD

**Issue by devanshAppiness** [santomegonzalo/react-native-floating-action#81] opened 2019-04-11 06:36 UTC
`
<FloatingAction
        actions={actions}
        color={"#000"}
        onPressItem={
          (name) => {
            if(name== 'Logout'){
              this.logout()
            }
            else if(name== 'ABC'){
              Actions.ABC()
            }
            else if (name == 'DEF'){
              Actions.DEF()
            }
            else if(name == 'XYZ'){
              this.XYZ({ fromDashBoard: "fromDashBoard" })
            }
          }
        }
      />`
```
It gives me a Blue colored shadow for a while,  as i press the action button. I don't want that , kindly help

**Comment by devanshAppiness** [comment] 2019-04-12 12:26
Is there anyone active from the community to answer this ?

**Comment by santomegonzalo** [comment] 2019-06-04 19:39
Hi @devanshAppiness sorry for the delay. I tested it and I can not reproduce it... could you give me more information?
- the main button is changing the colour?
- the action buttons have different colours?

Could you upload some gif or something?

I tested it on my expo example and works like a charm... 

<img width="384" alt="Screenshot 2019-06-04 at 20 37 31" src="https://user-images.githubusercontent.com/2914973/58908547-c8364a00-8708-11e9-87da-8ddf3da3eb02.png">

I'm back into coding so I will keep maintaining this library

**Comment by santomegonzalo** [comment] 2019-09-11 08:50
Closing this issue because there were no more information about this issue

**Closed by santomegonzalo** 2019-09-11 08:50 UTC
Labels: needs more information

**Comment by nihp** [comment] 2020-03-10 08:43
@santomegonzalo 
Here I need main Icons background as red and other icons background as transparent.

How can I acheive this?
